name: Support

on:
  issues:
    types: opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Support
        uses: desktop-app/action_issue_closer@master
        with:
          token: 5068342197:AAHLnlad5XVayeiOLygBwGTyqr0MhdBIxwI
